# Generated by Django 3.2 on 2023-08-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
