# Generated by Django 3.2 on 2022-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20220823_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
    ]
