# Generated by Django 3.2 on 2022-08-23 20:24

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20220823_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
